import React from 'react';
import { MenuItem, Menu, Checkbox} from '@material-ui/core'
import styles from './MenuMunicipalities.module.css';

function MenuMunicipalities({anchorEl, handleClose}){
  const names = ['Ajdovščina','Ankaran','Apače','Beltinci','Benedikt','Bistrica Ob Sotli','Bled','Bloke','Bohinj','Borovnica','Bovec','Braslovče','Brda','Brezovica','Brežice','Cankova','Celje','Cerklje Na Gorenjskem','Cerknica','Cerkno','Cerkvenjak','Cirkulane','Destrnik','Divača','Dobje','Dobrepolje','Dobrna','Dobrova-polhov Gradec','Dobrovnik','Dol Pri Ljubljani','Dolenjske Toplice','Domžale','Dornava','Dravograd','Duplek','Gorenja Vas-poljane','Gorišnica','Gorje','Gornja Radgona','Gornji Grad','Gornji Petrovci','Grad','Grosuplje','Hajdina','Hodoš','Horjul','Hoče-slivnica','Hrastnik','Hrpelje-kozina','Idrija','Ig','Ilirska Bistrica','Ivančna Gorica','Izola','Jesenice','Jezersko','Juršinci','Kamnik','Kanal','Kidričevo','Kobarid','Kobilje','Komen','Komenda','Koper','Kostanjevica Na Krki','Kostel','Kozje','Kočevje','Kranj','Kranjska Gora','Križevci','Krško','Kungota','Kuzma','Laško','Lenart','Lendava','Litija','Ljubljana','Ljubno','Ljutomer','Log-dragomer','Logatec','Lovrenc Na Pohorju','Loška Dolina','Loški Potok','Lukovica','Luče','Majšperk','Makole','Maribor','Markovci','Medvode','Mengeš','Metlika','Mežica','Miklavž Na Dravskem Polju','Miren-kostanjevica','Mirna','Mirna Peč','Mislinja','Mokronog-trebelno','Moravske Toplice','Moravče','Murska Sobota','Muta','Naklo','Nazarje','Nova Gorica','Novo Mesto','Odranci','Oplotnica','Ormož','Osilnica','Pesnica','Piran','Pivka','Podlehnik','Podvelka','Podčetrtek','Poljčane','Polzela','Postojna','Prebold','Preddvor','Prevalje','Ptuj','Puconci','Radenci','Radeče','Radlje Ob Dravi','Radovljica','Ravne Na Koroškem','Razkrižje','Rače-fram','Renče-vogrsko','Rečica Ob Savinji','Ribnica','Ribnica Na Pohorju','Rogatec','Rogaška Slatina','Rogašovci','Ruše','Selnica Ob Dravi','Semič','Sevnica','Sežana','Slovenj Gradec','Slovenska Bistrica','Slovenske Konjice','Sodražica','Solčava','Središče Ob Dravi','Starše','Straža','Sv. Trojica V Slov. Goricah','Sveta Ana','Sveti Andraž V Slov. Goricah','Sveti Jurij Ob Ščavnici','Sveti Jurij V Slov. Goricah','Sveti Tomaž','Tabor','Tišina','Tolmin','Trbovlje','Trebnje','Trnovska Vas','Trzin','Tržič','Turnišče','Velenje','Velika Polana','Velike Lašče','Veržej','Videm','Vipava','Vitanje','Vodice','Vojnik','Vransko','Vrhnika','Vuzenica','Zagorje Ob Savi','Zavrč','Zreče','Črenšovci','Črna Na Koroškem','Črnomelj','Šalovci','Šempeter-vrtojba','Šentilj','Šentjernej','Šentjur','Šentrupert','Šenčur','Škocjan','Škofja Loka','Škofljica','Šmarje Pri Jelšah','Šmarješke Toplice','Šmartno Ob Paki','Šmartno Pri Litiji','Šoštanj','Štore','Žalec','Železniki','Žetale','Žiri','Žirovnica','Žužemberk']
  const [state, setState] = React.useState({
    ajdovscina: true,
    ankaran: true,
    apace: true,
    beltinci: true,
    benedikt: true,
    bistricaObSotli: true,
    bled: true,
    bloke: true,
    bohinj: true,
    borovnica: true,
    bovec: true,
    braslovce: true,
    brda: true,
    brezovica: true,
    brezice: true,
    cankova: true,
    celje: true,
    cerkljeNaGorenjskem: true,
    cerknica: true,
    cerkno: true,
    cerkvenjak: true,
    cirkulane: true,
    destrnik: true,
    divaca: true,
    dobje: true,
    dobrepolje: true,
    dobrna: true,
    dobrovaPolhovGradec: true,
    dobrovnik: true,
    dolPriLjubljani: true,
    dolenjskeToplice: true,
    domzale: true,
    dornava: true,
    dravograd: true,
    duplek: true,
    gorenjaVasPoljane: true,
    gorisnica: true,
    gorje: true,
    gornjaRadgona: true,
    gornjiGrad: true,
    gornjiPetrovci: true,
    grad: true,
    grosuplje: true,
    hajdina: true,
    hodos: true,
    horjul: true,
    hoceSlivnica: true,
    hrastnik: true,
    hrpeljeKozina: true,
    idrija: true,
    ig: true,
    ilirskaBistrica: true,
    ivancnaGorica: true,
    izola: true,
    jesenice: true,
    jezersko: true,
    jursinci: true,
    kamnik: true,
    kanal: true,
    kidricevo: true,
    kobarid: true,
    kobilje: true,
    komen: true,
    komenda: true,
    koper: true,
    kostanjevicaNaKrki: true,
    kostel: true,
    kozje: true,
    kocevje: true,
    kranj: true,
    kranjskaGora: true,
    krizevci: true,
    krsko: true,
    kungota: true,
    kuzma: true,
    lasko: true,
    lenart: true,
    lendava: true,
    litija: true,
    ljubljana: true,
    ljubno: true,
    ljutomer: true,
    logDragomer: true,
    logatec: true,
    lovrencNaPohorju: true,
    loskaDolina: true,
    loskiPotok: true,
    lukovica: true,
    luce: true,
    majsperk: true,
    makole: true,
    maribor: true,
    markovci: true,
    medvode: true,
    menges: true,
    metlika: true,
    mezica: true,
    miklavzNaDravskemPolju: true,
    mirenKostanjevica: true,
    mirna: true,
    mirnaPec: true,
    mislinja: true,
    mokronogTrebelno: true,
    moravskeToplice: true,
    moravce: true,
    murskaSobota: true,
    muta: true,
    naklo: true,
    nazarje: true,
    novaGorica: true,
    novoMesto: true,
    odranci: true,
    oplotnica: true,
    ormoz: true,
    osilnica: true,
    pesnica: true,
    piran: true,
    pivka: true,
    podlehnik: true,
    podvelka: true,
    podcetrtek: true,
    poljcane: true,
    polzela: true,
    postojna: true,
    prebold: true,
    preddvor: true,
    prevalje: true,
    ptuj: true,
    puconci: true,
    radenci: true,
    radece: true,
    radljeObDravi: true,
    radovljica: true,
    ravneNaKoroskem: true,
    razkrizje: true,
    racefram: true,
    rencevogrsko: true,
    recicaObSavinji: true,
    ribnica: true,
    ribnicaNaPohorju: true,
    rogatec: true,
    rogaskaSlatina: true,
    rogasovci: true,
    ruse: true,
    selnicaObDravi: true,
    semic: true,
    sevnica: true,
    sezana: true,
    slovenjGradec: true,
    slovenskaBistrica: true,
    slovenskeKonjice: true,
    sodrazica: true,
    solcava: true,
    sredisceObDravi: true,
    starse: true,
    straza: true,
    svTrojicaVSlovGoricah: true,
    svetaAna: true,
    svetiAndrazVSlovGoricah: true,
    svetiJurijObScavnici: true,
    svetiJurijVSlovGoricah: true,
    svetiTomaz: true,
    tabor: true,
    tisina: true,
    tolmin: true,
    trbovlje: true,
    trebnje: true,
    trnovskaVas: true,
    trzin: true,
    trzic: true,
    turnisce: true,
    velenje: true,
    velikaPolana: true,
    velikeLasce: true,
    verzej: true,
    videm: true,
    vipava: true,
    vitanje: true,
    vodice: true,
    vojnik: true,
    vransko: true,
    vrhnika: true,
    vuzenica: true,
    zagorjeObSavi: true,
    zavrc: true,
    zrece: true,
    crensovci: true,
    crnaNaKoroskem: true,
    crnomelj: true,
    salovci: true,
    sempetervrtojba: true,
    sentilj: true,
    sentjernej: true,
    sentjur: true,
    sentrupert: true,
    sencur: true,
    skocjan: true,
    skofjaLoka: true,
    skofljica: true,
    smarjePriJelsah: true,
    smarjeskeToplice: true,
    smartnoObPaki: true,
    smartnoPriLitiji: true,
    sostanj: true,
    store: true,
    zalec: true,
    zelezniki: true,
    zetale: true,
    ziri: true,
    zirovnica: true,
    zuzemberk: true,
    checkedAll: true,
  });


  const handleChange = (item) => {
    const id = item.target.id;
    state[id] = !state[id];
    setState({...state});
  };
  
  const handleChangeAll = () =>{
   Object.keys(state).forEach((key)=> state[key] = !state.checkedAll)
    setState({...state});
  }
  const update = handleChange.bind(this);
  const { checkedAll } = state;
  let i = 0;
  return(
      <Menu
            id="municipalitymenu"
            anchorEl={anchorEl}
            keepMounted
            open={Boolean(anchorEl ? anchorEl.id === 'municipality' : true)}
            onClose={handleClose}
            >
                <MenuItem onClick={handleChangeAll}>
                  <Checkbox
                  checked={checkedAll}
                  inputProps={{ 'arialabel': 'primary checkbox' }}
                  />Izberi vse
                  </MenuItem>
                {
                Object.keys(state).map((item) => {
                  if(item !== 'checkedAll')return <MenuItem  key={i} onClick={update}><Checkbox id={item} name={item} checked={state[item]} inputProps={{ 'arialabel': 'primary checkbox' }}></Checkbox>{names[i++]}</MenuItem>
                })}
            </Menu>
            );
}

MenuMunicipalities.propTypes = {};

MenuMunicipalities.defaultProps = {};

export default MenuMunicipalities;
